name: gym_app
description: A new Flutter project.
# Cache bust for UI Polish 2
publish_to: "none"
version: 1.7.3+56

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: any
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  flutter_svg: ^2.0.7
  fl_chart: ^0.66.0
  # Add other dependencies as needed

  collection: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  uuid: ^4.5.2
  xml: ^6.6.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  url_strategy: ^0.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
