name: gym_app
description: A new Flutter project.
# Cache bust for UI Polish 2
publish_to: 'none'
version: 1.2.29+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: any
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  flutter_svg: ^2.0.7
  # Add other dependencies as needed

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
